
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: golang-demo
  annotations:
    backstage.io/kubernetes-id: golang-demo
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage-collection/golang-demo
spec:
  type: api
  system: system:default/examples
  lifecycle: production
  owner: group:default/developers
